import { CCIDynamicBotOptions } from './bot';

export const BTCUSDT: CCIDynamicBotOptions = {
    instrumentType: 'FUTURES',
    fee: 0.02,
    lotsMultiplier: 1,
    equityLevel: 1,
    broker: 'binance',
    ticker: 'BTCUSDT',
    currency: 'USDT',
    interval: '15min',
    amount: 500,
    orderCandlesLimit: 76,
    closeAtZero: false,
    stopTakeRatio: 1.47,
    atrPeriod: 30,
    atrMultiplier: 3.45,
    levelPeriod: 31,
    levelRedunant: 0.84,
    levelSampleCount: 2,
    levelSampleType: 2,
    levelMultiplier: 2.38,
    levelOffset: 0,
    cciPeriod: 35,
    zeroClose: true,
    sandbox: true,
    cciAtr: false,
    maxRetryOrders: 3,
    reduceWhen: 1.05,
    reduceSize: 0.22,
    manual: true,
    id: 4,
    signalFilter: false,
    takeProfit: 8.74,
    stopLoss: 9.1,
    trailing: 2,
};

export const SBER: CCIDynamicBotOptions = {
    instrumentType: 'SPOT',
    fee: 0.02,
    lotsMultiplier: 1,
    equityLevel: 1,
    broker: 'tinkoff',
    ticker: 'SBER',
    currency: 'RUB',
    interval: '15min',
    amount: 500,
    maxRetryOrders: 0,
    orderCandlesLimit: 100,
    closeAtZero: false,
    stopTakeRatio: 2,
    atrPeriod: 21,
    atrMultiplier: 5.48,
    levelPeriod: 30,
    levelRedunant: 0.27,
    levelSampleCount: 2,
    levelSampleType: 2,
    levelMultiplier: 1,
    levelOffset: 0,
    cciPeriod: 13,
    zeroClose: false,
    sandbox: true,
    cciAtr: false,
    id: 29,
};
