import { SpikesGOptions } from './bot';

export const YFIIUSDT: SpikesGOptions = {
    broker: 'binance',
    ticker: 'YFIIUSDT',
    currency: 'USDT',
    interval: '15min',
    amount: 500,
    fee: 0.1,
    eventExpireBars: 34,
    takeProfit: 1.07,
    stopLoss: 30,
    step: 1.91,
    levelsCount: 2,
    martingale: 1.25,
    fibo: false,
    barsTrend: 33,
    reversed: true,
    bandsPeriod: 13,
    bandsDev: 1.55,
    usePeaks: true,
    buyOnly: false,
    margin: true,
    useClose: false,
    id: 29,
    lotsMultiplier: 1,
};

export const RVNUSDT: SpikesGOptions = {
    broker: 'binance',
    ticker: 'RVNUSDT',
    currency: 'USDT',
    interval: '15min',
    amount: 500,
    fee: 0.1,
    eventExpireBars: 62,
    takeProfit: 8,
    stopLoss: 30,
    step: 5,
    levelsCount: 3,
    martingale: 1.59,
    fibo: false,
    barsTrend: 58,
    reversed: true,
    bandsPeriod: 28,
    bandsDev: 2.68,
    usePeaks: true,
    buyOnly: false,
    margin: true,
    useClose: false,
    id: 29,
    lotsMultiplier: 1,
};

export const XTZUSDT: SpikesGOptions = {
    broker: 'binance',
    ticker: 'XTZUSDT',
    currency: 'USDT',
    interval: '15min',
    amount: 500,
    fee: 0.1,
    eventExpireBars: 52,
    takeProfit: 1.23,
    stopLoss: 30,
    step: 1.27,
    levelsCount: 3,
    martingale: 1.83,
    fibo: false,
    barsTrend: 43,
    reversed: true,
    bandsPeriod: 64,
    bandsDev: 1.42,
    usePeaks: true,
    buyOnly: false,
    margin: true,
    useClose: false,
    id: 29,
    lotsMultiplier: 1,
};

export const ONTUSDT: SpikesGOptions = {
    broker: 'binance',
    ticker: 'ONTUSDT',
    currency: 'USDT',
    interval: '15min',
    amount: 500,
    fee: 0.1,
    eventExpireBars: 33,
    takeProfit: 1.06,
    stopLoss: 30,
    step: 2.79,
    levelsCount: 3,
    martingale: 1.68,
    fibo: false,
    barsTrend: 45,
    reversed: true,
    bandsPeriod: 30,
    bandsDev: 1.44,
    usePeaks: true,
    buyOnly: false,
    margin: true,
    useClose: false,
    id: 29,
    lotsMultiplier: 1,
};

export const XRPUSDT: SpikesGOptions = {
    broker: 'binance',
    ticker: 'XRPUSDT',
    currency: 'USDT',
    interval: '15min',
    amount: 500,
    fee: 0.1,
    eventExpireBars: 28,
    takeProfit: 1.69,
    stopLoss: 30,
    step: 1.71,
    levelsCount: 3,
    martingale: 1.95,
    fibo: false,
    barsTrend: 11,
    reversed: true,
    bandsPeriod: 10,
    bandsDev: 1.98,
    usePeaks: true,
    buyOnly: false,
    margin: true,
    useClose: false,
    id: 29,
    lotsMultiplier: 1,
};

export const ETHUSDT: SpikesGOptions = {
    broker: 'binance',
    ticker: 'ETHUSDT',
    currency: 'USDT',
    interval: '15min',
    amount: 500,
    fee: 0.1,
    eventExpireBars: 22,
    takeProfit: 2.47,
    stopLoss: 30,
    step: 2.55,
    levelsCount: 3,
    martingale: 1.67,
    fibo: false,
    barsTrend: 20,
    reversed: true,
    bandsPeriod: 36,
    bandsDev: 2.09,
    usePeaks: false,
    buyOnly: false,
    margin: true,
    useClose: false,
    id: 29,
    lotsMultiplier: 1,
};

export const XMRUSDT: SpikesGOptions = {
    broker: 'binance',
    ticker: 'XMRUSDT',
    currency: 'USDT',
    interval: '15min',
    amount: 500,
    fee: 0.1,
    eventExpireBars: 32,
    takeProfit: 2.08,
    stopLoss: 30,
    step: 3.18,
    levelsCount: 3,
    martingale: 1.64,
    fibo: false,
    barsTrend: 25,
    reversed: true,
    bandsPeriod: 59,
    bandsDev: 1.59,
    usePeaks: true,
    buyOnly: false,
    margin: true,
    useClose: false,
    id: 29,
    lotsMultiplier: 1,
};
