import { SpikesGOptions } from './bot';

export const EGLDUSDT: SpikesGOptions = {
    instrumentType: 'FUTURES',
    broker: 'binance',
    ticker: 'EGLDUSDT',
    currency: 'USDT',
    interval: '15min',
    amount: 500,
    fee: 0.1,
    eventExpireBars: 33,
    takeProfit: 7.31,
    stopLoss: 30,
    step: 10.81,
    levelsCount: 3,
    martingale: 1.8,
    fibo: false,
    barsTrend: 43,
    reversed: true,
    bandsPeriod: 74,
    bandsDev: 3.33,
    usePeaks: true,
    buyOnly: false,
    margin: true,
    useClose: false,
    id: 4,
    lotsMultiplier: 1,
};

export const FILUSDT: SpikesGOptions = {
    broker: 'binance',
    ticker: 'FILUSDT',
    currency: 'USDT',
    interval: '15min',
    amount: 500,
    fee: 0.1,
    eventExpireBars: 67,
    takeProfit: 1.56,
    stopLoss: 30,
    step: 2.43,
    levelsCount: 3,
    martingale: 1.77,
    fibo: false,
    barsTrend: 35,
    reversed: true,
    bandsPeriod: 57,
    bandsDev: 2.03,
    usePeaks: true,
    buyOnly: false,
    margin: true,
    useClose: false,
};
